apiVersion: v1
kind: Service
metadata:
  name: nginx
  # service labels
  labels:
    project: roboshop
    environment: dev
spec:
# service uses the below labes to select the pod
  selector:
    project: roboshop
    component: frontend
    tire: frontend
  ports:
    - protocol: TCP
      port: 80 # service port 
      targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx # pod name
  labels:
    project: roboshop
    environment: dev
    component: frontend
    tire: frontend
spec:
  containers:
  - name: nginx # container name
    image: nginx # by default it will get from docker hub
    
