apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  # service labels
  labels:
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
# service uses the below labes to select the pod
  selector:
    project: roboshop
    component: frontend
    tire: frontend
  ports:
    - protocol: TCP
      port: 80 # service port 
      targetPort: 80 # container port
      nodePort: 30008